# Generated by Django 4.2.19 on 2025-03-04 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='duration',
            new_name='party_size',
        ),
    ]
